### ISSUE TITLE
No module named 'read_clustering'

### ISSUE THREAD

**Issue by AminaLEM** [adbailey4/yeast_rrna_modification_detection#5]
Hello @adbailey4 , 

Could you please point me to the package `read_clustering` you used in your Jupyter notebooks? seems not included within your installation environment. 

PS. I tested that using a container of your docker image.

Thank you, 

Amina

**Comment by adbailey4** [comment]
Apologies, I thought I removed that as a dependency. Which notebook is it used in? 

You can find the repo here https://github.com/adbailey4/read_clustering

**Comment by AminaLEM** [comment]
One of the notebooks is "generate_summary_data.ipynb"

**Comment by adbailey4** [comment]
Now that I look back at my documentation, I see that I do say it needs to be installed for the notebooks. I updated the documentations to README.md's so they will be easier to find when exploring the repo on github

see https://github.com/adbailey4/yeast_rrna_modification_detection/tree/main/notebooks
